spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/edutrack

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt:
    secret: edutrack-dev-secret-key-change-me-before-prod-32bytes
    access-token-expiration-ms: 86400000